"""Shared graph relation labels used across ingest, enrichment, and analysis."""

HTTP_CALLS_ROUTE = "HTTP_CALLS_ROUTE"
ROUTE_READS_TABLE = "ROUTE_READS_TABLE"
ROUTE_WRITES_TABLE = "ROUTE_WRITES_TABLE"
ROUTE_CALLS_RPC = "ROUTE_CALLS_RPC"
ROUTE_GUARDED_BY_RLS = "ROUTE_GUARDED_BY_RLS"
TASK_ENQUEUES = "TASK_ENQUEUES"
TASK_CONSUMES = "TASK_CONSUMES"
PRODUCES_PAYLOAD = "PRODUCES_PAYLOAD"
CONSUMES_PAYLOAD = "CONSUMES_PAYLOAD"
SCHEMA_DEFINED_BY_MIGRATION = "SCHEMA_DEFINED_BY_MIGRATION"
MIGRATION_PRECEDES = "MIGRATION_PRECEDES"
DECLARES_DEP = "DECLARES_DEP"
RESOLVES_TO = "RESOLVES_TO"
PEER_OF = "PEER_OF"
IMPORTS_PACKAGE = "IMPORTS_PACKAGE"
READS_ENV_VAR = "READS_ENV_VAR"
WRITES_ENV_VAR = "WRITES_ENV_VAR"
DEFINED_BY_CONFIG = "DEFINED_BY_CONFIG"
RENDERED_BY_PROMPT = "RENDERED_BY_PROMPT"
PROMPT_DECLARES_VAR = "PROMPT_DECLARES_VAR"
PROMPT_USES_VAR = "PROMPT_USES_VAR"
IMPLEMENTS_OPENAPI_OP = "IMPLEMENTS_OPENAPI_OP"
CONSUMES_OPENAPI_OP = "CONSUMES_OPENAPI_OP"
SCHEMA_OF = "SCHEMA_OF"
NEXT_ROUTE_GUARDED_BY_MIDDLEWARE = "NEXT_ROUTE_GUARDED_BY_MIDDLEWARE"
NEXT_ROUTE_USES_LAYOUT = "NEXT_ROUTE_USES_LAYOUT"
WORKFLOW_USES_SECRET = "WORKFLOW_USES_SECRET"
SERVICE_DEPENDS_ON = "SERVICE_DEPENDS_ON"
STAGE_COPIES_PATH = "STAGE_COPIES_PATH"

__all__ = [
    "HTTP_CALLS_ROUTE",
    "ROUTE_READS_TABLE",
    "ROUTE_WRITES_TABLE",
    "ROUTE_CALLS_RPC",
    "ROUTE_GUARDED_BY_RLS",
    "TASK_ENQUEUES",
    "TASK_CONSUMES",
    "PRODUCES_PAYLOAD",
    "CONSUMES_PAYLOAD",
    "SCHEMA_DEFINED_BY_MIGRATION",
    "MIGRATION_PRECEDES",
    "DECLARES_DEP",
    "RESOLVES_TO",
    "PEER_OF",
    "IMPORTS_PACKAGE",
    "READS_ENV_VAR",
    "WRITES_ENV_VAR",
    "DEFINED_BY_CONFIG",
    "RENDERED_BY_PROMPT",
    "PROMPT_DECLARES_VAR",
    "PROMPT_USES_VAR",
    "IMPLEMENTS_OPENAPI_OP",
    "CONSUMES_OPENAPI_OP",
    "SCHEMA_OF",
    "NEXT_ROUTE_GUARDED_BY_MIDDLEWARE",
    "NEXT_ROUTE_USES_LAYOUT",
    "WORKFLOW_USES_SECRET",
    "SERVICE_DEPENDS_ON",
    "STAGE_COPIES_PATH",
]
